from fastapi import APIRouter, UploadFile, File, Form
from pydantic import BaseModel
from typing import List, Dict, Any
from datetime import datetime
import uuid
import json
import boto3
import pandas as pd
from io import StringIO
import os
from dotenv import load_dotenv
import google.generativeai as genai

load_dotenv()

router = APIRouter()

# ENV Config
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")
S3_BUCKET = os.getenv("S3_BUCKET", "neuroflow-data")
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_REGION = os.getenv("AWS_REGION", "us-east-1")

# AWS Client
s3_client = boto3.client(
    's3',
    aws_access_key_id=AWS_ACCESS_KEY_ID,
    aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
    region_name=AWS_REGION
)

# Gemini Client
if GOOGLE_API_KEY:
    genai.configure(api_key=GOOGLE_API_KEY)
    model = genai.GenerativeModel('gemini-1.5-flash')
else:
    model = None

class WorkflowStep(BaseModel):
    name: str
    type: str
    config: Dict[str, Any] = {}

class Workflow(BaseModel):
    id: str
    name: str
    description: str
    natural_language: str
    steps: List[WorkflowStep]
    status: str
    logs: List[str]
    s3_output: str = ""
    created_at: datetime

@router.post("/workflows")
async def create_workflow(
    name: str = Form(default="AI Pipeline"),
    description: str = Form(default="Generated by NeuroFlow"),
    natural_language: str = Form(...),
    file: UploadFile = File(None)
) -> Workflow:
    """Create complete AI data pipeline"""
    
    # Generate AI steps
    steps = []
    if model:
        try:
            prompt = f'Convert "{natural_language}" to JSON pipeline steps. Types: upload,clean,analyze,store,notify. Return ONLY JSON array.'
            response = model.generate_content(prompt)
            json_text = response.text.strip()
            start = json_text.find('[')
            end = json_text.rfind(']') + 1
            if start >= 0:
                steps_data = json.loads(json_text[start:end])
                steps = [WorkflowStep(**s) for s in steps_data]
        except:
            pass
    
    if not steps:
        # Fallback
        steps = [
            WorkflowStep(name="Upload Data", type="upload"),
            WorkflowStep(name="Clean Data", type="clean"),
            WorkflowStep(name="Analyze", type="analyze"),
            WorkflowStep(name="Store Results", type="store")
        ]
    
    # Create workflow
    workflow = Workflow(
        id=str(uuid.uuid4()),
        name=name,
        description=description,
        natural_language=natural_language,
        steps=steps,
        status="completed",
        logs=["🤖 AI Pipeline Generated!"],
        created_at=datetime.utcnow()
    )
    
    # Process file if uploaded
    if file and file.filename:
        try:
            content = await file.read()
            input_key = f"uploads/{uuid.uuid4()}-{file.filename}"
            
            # Upload to S3
            s3_client.put_object(Bucket=S3_BUCKET, Key=input_key, Body=content)
            
            # Process CSV
            df = pd.read_csv(StringIO(content.decode('utf-8')))
            clean_rows = len(df.dropna())
            
            workflow.logs.extend([
                f"📥 Loaded: {len(df)} rows",
                f"🧹 Cleaned: {clean_rows} rows",
                f"📊 Columns: {list(df.columns)}",
                f"💾 Stored: s3://{S3_BUCKET}/{input_key}"
            ])
            workflow.s3_output = f"s3://{S3_BUCKET}/{input_key}"
            
        except Exception as e:
            workflow.logs.append(f"⚠️ File error: {str(e)}")
    
    return workflow